### ISSUE TITLE
redis经纬度数据操作，支持按照距离远近排序吗？

### ISSUE THREAD

**Issue by feng99** [krislinzhao/StudyNotes#3]
比如，我周围3公里有20个商家，按照由近到远排序。

**Comment by feng99** [comment]
找到了，有个排序的条件
建议在文档里补充下，因为这个比较贴合业务场景。

**Comment by krislinzhao** [comment]
通过 georadius的参数asc由近及远的排序，已在**08.经纬度数据操作**这节添加了详细的参数说明。

**Comment by feng99** [comment]
> 通过 georadius的参数asc由近及远的排序，已在**08.经纬度数据操作**这节添加了详细的参数说明。

经过实际的业务考虑,我最终选择用mongoDB来实现这个功能,
因为redis虽然能实现具体范围查找和排序  
但是无法增加其他条件   比如只看附近3公里 参加618活动的商家  并按照距离由近及远排序.
甚至是单页面数据  多个查询条件 多个排序条件    混合使用的
比如  按照价格排序    然后可以切换为按照距离排序   
redis除了地理位置   再扩展一点的都不支持了.
单独维护一份地理位置数据  又不值得  因为只要有数据拷贝,就有数据不一致问题.
感谢老铁回复问题.
