### ISSUE TITLE
文档勘误反馈

### ISSUE THREAD

**Issue by hashqueue** [krislinzhao/StudyNotes#6]
`StudyNotes/Docker/03.Docker 常用命令.md`中的`2.镜像命令`title下的`MAGE ID：镜像ID`中的`MAGE`少了个`I`。
正好在跟着大佬学习，我帮你review一下文档，嘿嘿~

**Comment by krislinzhao** [comment]
非常感谢，自己有点不仔细啊，欢迎继续勘误。
